services:
  php:
    build: ./php
    container_name: php-fpm
    user: "${UID:-1000}:${GID:-1000}"   
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8080:80" 
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

